[project]
name = 'Spontaneity-Scheduling-Optimization-Suite'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.improvisation-rehearsal-management-system]
path = 'contracts/improvisation-rehearsal-management-system.clar'
clarity_version = 3
epoch = 'latest'

[contracts.random-adventure-deterministic-algorithm]
path = 'contracts/random-adventure-deterministic-algorithm.clar'
clarity_version = 3
epoch = '3.2'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
